apiVersion: v1
kind: Service
metadata:
  name: cloudpose-service
  namespace: cloudpose
spec:
  type: NodePort
  selector:
    app: cloudpose
  ports:
    - protocol: TCP
      port: 80
      targetPort: 60001
      nodePort: 30007
